### PR TITLE
Fix minor typo

### PR DESCRIPTION
**Pull request by akissa**

### CODE REVIEW

**Comment by swilmet** [comment]
What did you change? In the GitHub diff view, I cannot see what changed.

**Comment by akissa** [comment]
- An event loop listens some sources of events
+ An event loop listens to some sources of events.

**Comment by swilmet** [comment]
Ok thanks, I've pushed commit e48f12e137290182db096aa6c3dbd8b134fc0f29.

And I've added you to the acknowledgments section. Even small contributions are welcome ;) Thanks!

**Comment by akissa** [comment]
Thank you for your work much appreciated.

**Pull request closed without merging**
